version: '2'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zou970514
    ports:
      - 27017:27017
    container_name: mongo_ins
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: zou970514
    container_name: mongo_express_ins
